### ISSUE TITLE
Unable to view teams in evaluate team section

### ISSUE THREAD

**Issue by tangwr** [nusskylab/nusskylab#166]
![q](https://cloud.githubusercontent.com/assets/12490000/7952007/657b3518-09e1-11e5-9104-31f1ab0da9b8.JPG)

Both my friend and I are uable to view any team in the evaluate team section:

Team Number: 125
A0125531R         Tang Wei Ren 
A0133267H         Muhammad Razali Bin Sa Mohd Yacob

**Comment by franklingu** [comment]
because of some mismatches of team names in the sheet and in the system, some evaluation relations are not imported correctly. All advisers are adjusting the spreadsheet manually now. It is a tedious process and therefore some time needed. So your patience and understanding will be much appreciated.

Plus, some advisers are not updating the sheet, meaning that I will have to go through in the end--which means some more time needed

**Comment by tangwr** [comment]
ok thanks for the update and information.
