### ISSUE TITLE
NUS OpenID redirection not working on dev server

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#319]

**Comment by franklingu** [comment]
seems to be working on local server. need to check server log

**Comment by franklingu** [comment]
Seems the issue was with "/tmp/[some folder]" not found, which is used by omniauth now for login. change this to be the current directory/tmp/ for safety. And guess for this happening is that there was some maintenance work or something that just removes /tmp completely

**Comment by franklingu** [comment]
Also, we should try to encourage use of email + password login as that is completely controlled by us.

@knmnyn

**Comment by knmnyn** [comment]
Noted.  Thanks for fixing the problem.

NUSNET sign in will be a lot easier for most, so that's why we should
continue to support NUSNET sign-in.  But we can ask the students to also
associate a password for their account for local login.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
