### ISSUE TITLE
add rich text editing feature

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#50]
tinyMCE maybe a bit overkill for this. may need to research a bit later.

**Comment by franklingu** [comment]
or maybe we can just use markdown instead? @knmnyn

**Comment by franklingu** [comment]
http://www.tinymce.com/

or something even lighter

**Comment by Leventhan** [comment]
TinyMCE was a pain to set up in a previous Rails project. I don't recommend it. I haven't tried this, but https://github.com/kreativgebiet/rich looks promising.

**Comment by knmnyn** [comment]
I've done tinyMCE before, but don't know whether it plays well with Rails
(anymore).  Markdown is fine, and is more portable these days but is there
a WYSIWYG one?


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
markdown wysiwyg editors are definitely available. and compared to markup, this kind of editor is of smaller size. however, for first time users, markdown may require some learning at first(although this should not be a big problem to SoC students). ckeditor is even larger if the feature set is comparable to tinymce. But surely the problem with tinymce with rails will be considered.

https://github.com/benweet/stackedit

**Comment by knmnyn** [comment]
Up to you.  I prefer more stable third party libs than bleeding edge,
especially since many die after 2-3 years.  We won't always have you around
to support your Skylab... :-)


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
okay. noted. previously I did a bit of search on this issue for teammates when I was doing comments feature, guess I will pull content over and create documentation for this issue
