### ISSUE TITLE
Reordering entries on the staff page

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#517]
Currently the list of facilitators is ordered by name so I am listed at the bottom of the list of the facilitators. 

There needs to be a way to reorder the list. Otherwise, the students will be contacting Min for their questions (which has already happened quite a few times so far).

**Comment by knmnyn** [comment]
Perhaps easiest to just remove me as a facilitator so that the queries come
to you... !


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by njyjn** [comment]
@zhaojin42 I can add a line of text above to direct any enquiries straight to you :-) Let me know if it is ok.

<img width="980" alt="screen shot 2017-03-07 at 20 30 43" src="https://cloud.githubusercontent.com/assets/10694375/23656526/0c23ec46-0375-11e7-928a-0abab8b964b0.png">

**Comment by R-D-D-D** [comment]
@zhaojin42 Added a feature to sort the facilitators based on oldest, newest, name and display order, can include more option if need be, feature using AJAX so no page reload.
Sort by name:
<img width="922" alt="Screenshot 2020-02-21 at 11 42 22 PM" src="https://user-images.githubusercontent.com/45935526/75049001-691d9d00-5504-11ea-9d67-923370e6676f.png">

Sort by oldest:
<img width="922" alt="Screenshot 2020-02-21 at 11 42 07 PM" src="https://user-images.githubusercontent.com/45935526/75049076-881c2f00-5504-11ea-9a6b-888eec10b6dc.png">
