### ISSUE TITLE
Create appropriate fixture data to deploy with the system

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#560]
The initial deployment of skylab should come with some simple fixture data (sample students, teams, projects, forums posts) so that (unit | integration) tests can be used to test the integrity of the project.  Mention commits that partially address this issue.

**Comment by knmnyn** [comment]
Bump.

**Comment by chowyb** [comment]
Adding a few other things that may be needed for fixture data (other devs are free to add in their own):

1. Add a Milestone 1 for the current cohort, as well as a submission survey template for Milestone 1, containing at least 1 question. Otherwise, users are unable to register as a student (due to Ruby's equivalent of a null pointer exception).
2. Add at least 1 team. Otherwise, students are unable to invite team members.

**Comment by chowyb** [comment]
Reopening as issue is not completely fixed yet.

**Comment by zhaojin42** [comment]
@potatowagon please discuss with the rest and create a consolidated test of fixture data for general use.

**Comment by zhaojin42** [comment]
For fresh installations, additional fixture data need to be added for some of the pages to work.

For example, for the project page, a team of two students with an adviser should be added.

**Comment by e0003133** [comment]
After running:
bundle exec rake db:fixtures:load RAILS_ENV="development"

the fixture data present is: 
Students in 2019 and 2018
Advisers in 2019 and 2018
Mentors in 2019 and 2018
Admins in 2019 and 2018
project teams in 2019 and 2018
3 survey templates for milestones 1 2 3
teams in 2019 and 2018
2 evaluating relations in 2019

developers, do see what else is needed to sufficiently test / try all the features
