### ISSUE TITLE
Cascade student deletion to team

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#679]
If a student in a team is deleted, the corresponding team should also be removed.

**Comment by zhaojin42** [comment]
Even if this is not the default behavior, it would be good to have a prompt asking whether the team should be deleted as well.

**Comment by Kennard123661** [comment]
@zhaojin42 Hi Prof Jin, just to check. If the student is deleted, it would trigger the team to be deleted. If the team is deleted, the other student in the team will also be deleted based on the constraints set by in the team database. Should all students be deleted if a team is deleted? Because there is another tab that deletes teams as well

**Comment by zhaojin42** [comment]
Team deletion should not lead to student deletion. =)

If a student in a team is deleted, the other student in the same team (if any) should be removed from the team, and the team should be deleted.
