### ISSUE TITLE
Urgent: Adviser is unable to submit evaluation for Milestone 2

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#733]
I have stepped through the evaluation process and noticed that the Adviser is unable to submit evaluation for Milestone 2. (Preview as Demo Adviser 1 -> Start evaluation on Demo Team 1's Milestone 2 submission). 

This is possibly related to #707. @JunWei96 

Please fix this as soon as possible and make sure that the adviser is able to view/create/submit evaluation. Thanks!

(Somehow a team is able to submit peer evaluation without any problem.)

**Comment by JunWei96** [comment]
From my testing in development environment, it seems like a regression caused by #712. In this PR, there was a change in this [line](https://github.com/nusskylab/nusskylab/commit/93bfa06edbe6a398c9d5935dd6b4e7086e504032#diff-b226c4041028209d3eda291727e9d42eR15). When I revert this change, the peer evaluation works fine.
@aaditkamat, can explain the reason for the change.

**Comment by aaditkamat** [comment]
I think I might have changed it to `params[:submission_id]` because I was getting submission as nil when I used `params[:target]`. If submission is nil, then it causes an error when accessing the id in the next line. Perhaps, if the peer evaluation works fine by reverting this change, then we can add a nil check like this:
```ruby
submission = Submission.find_by(id: params[:target])
if not submission.nil?
   peer_evaluation = PeerEvaluation.find_by(
        adviser_id: params[:adviser_id],
        submission_id: submission.id
      )
end
```

**Comment by JunWei96** [comment]
Okay, can you create a PR for it?

**Comment by aaditkamat** [comment]
I'm not able to currently test the changes but I am adding this as per @JunWei96's suggestion

**Comment by JunWei96** [comment]
I don't have my laptop with me currently so I will not be able to test it till night time. @bokwoon95 are you available to test this?

**Comment by bokwoon95** [comment]
Yup I've just tried it and the Demo Adviser can now start the evaluation 
![output](https://user-images.githubusercontent.com/23723357/60479553-d0a68400-9cb8-11e9-95ef-53bfa2ade178.gif)
