### ISSUE TITLE
Teams editing milestone submission after deadline

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#736]
As of now, the teams are allowed to edit their milestone submissions after deadline for purposes such as adding more information for peer evaluation.

However, sometimes this feature causes some panic among the students if they accidentally click "edit"->"update submission", which causes the "last updated at" to be updated and turn red.

Suggestions are welcome on how to change this.

**Comment by aaditkamat** [comment]
Not sure how we can rectify this because we can't tell whether the student wants to/doesn't want to edit the submission. The only thing I can think of is to not change the last updated at if there has been no change in submission (have a versioning system in place for the submissions and then diff between current and previous versions).
