### ISSUE TITLE
Feature to monitor submission status for peer evaluation

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#776]
The advisers should be able to see whether a team has competed the peer evaluation for another team. 

So for example, if Team A is supposed to evaluate Team B and C. There should be a page showing that the peer evaluations from A to B, and from A to C have been submitted.

**Comment by jjlee050** [comment]
@zhaojin42 This feature has already been implemented prior to the creation of this issue. 
See below of screenshots.
![Screenshot 2020-02-15 at 15 02 29](https://user-images.githubusercontent.com/5901764/74583662-42430080-5004-11ea-92ac-6689f38fbfec.png)

You can access the team panel of any adviser to test the feature. If a team has submitted a peer evaluation of the evaluating team, adviser is able to see the full peer evaluation form. If a team has not submitted a peer evaluation, it will be disabled. However, if a team has dropped from orbital, the button will still remained disabled instead of cancelled or remove. I can work on improving this instead.

**Comment by zhaojin42** [comment]
Good. Thanks for the clarification. ^_^ I will close this issue then.
